### ISSUE TITLE
So, how are we going to handle commits here?

### ISSUE THREAD

**Issue by Sslaxx** [BlitzerSIO/grass-cheetah#1]
At the moment all I see is the ZIP file of (what I assume to be) the last good Master commit.

I would assume you're not expecting uploads as ZIP files either but expecting the same structure from Bitbucket to be recreated here (as best practice) - separate branches merged into master when ready. Is this correct?

**Comment by BlitzerSIO** [comment]
Yes sir.

**Comment by Sslaxx** [comment]
Gotcha.
